/**
 * Curated market horsepower catalog (public docs as of mid-2026).
 * Used by the Market Deep Dive page — separate from the Geoff Thermometer home.
 */

export const marketCatalog = {
  updatedNote:
    "Quotes mix uneven units on purpose: Geoff = shared Token Plan pool; Grok/OpenAI = $ / 1M meters; Copilot = seats. Live status is sniffed separately. Verify on official pages before you buy.",
  vendors: [
    {
      id: "geoff",
      name: "Geoff / Stacknet",
      company: "hwonder · geoff.ai",
      color: "#34d399",
      tagline: "Universal Token Plan capacity · multimodal story utility",
      delivers: [
        "Shared monthly token pool across chat, image, music, video, voice, code, agents",
        "Public /v1/models cards (5) + ~29 network routing lanes — not the same list",
        "Creative shadow booster for storytelling — not a sealed chatbot seat",
        "Built by hwonder — Token Plan tables on docs.geoff.ai",
      ],
      horsepower: {
        flagship: "magma",
        context: "Network-routed (varies by model lane)",
        maxContextLabel: "Lane-dependent · pyro:max docs say 1M",
        modalities: ["text", "image", "music", "video", "voice", "code", "agents"],
        apiStyle: "App + Stacknet RPC / OpenAI-compatible /v1/models",
        pricingModel:
          "Token Plan seats: Basic $19 / Pro $199 / Max $499 / Turbo $999 (monthly token pool)",
      },
      models: [
        {
          id: "magma",
          role: "Creative powerhouse",
          context: "1M (docs)",
          input: "plan tokens",
          output: "plan tokens",
          notes: "SOTA media + agents · public /v1/models card · shared pool",
        },
        {
          id: "pyro",
          role: "Companion reasoning brain",
          context: "Network",
          input: "plan tokens",
          output: "plan tokens",
          notes: "Live API card — replaced older duce naming on Stacknet",
        },
        {
          id: "pyro:max",
          role: "Max reasoning lane",
          context: "1M (docs)",
          input: "plan tokens",
          output: "plan tokens",
          notes: "Heavier pyro-class multimodal chat",
        },
        {
          id: "preview",
          role: "Everyday multimodal",
          context: "Network",
          input: "plan tokens",
          output: "plan tokens",
          notes: "Fast text/vision + tools lane",
        },
        {
          id: "stack-embed",
          role: "Embeddings",
          context: "Network",
          input: "plan tokens",
          output: "plan tokens",
          notes: "Retrieval / search memory card on /v1/models",
        },
        {
          id: "network lanes (~29)",
          role: "Routing map",
          context: "stack-chat/media/vision/voice × layers",
          input: "n/a",
          output: "n/a",
          notes: "From /network/summary — internal lanes, not extra seat SKUs",
        },
        {
          id: "Basic → Turbo seats",
          role: "Billing tiers",
          context: "150M → 20B tokens/mo",
          input: "$19 → $999/mo",
          output: "shared pool",
          notes: "See docs.geoff.ai/token-plan — RPM/TPM scale with plan",
        },
      ],
      research: [
        { label: "geoff.ai", href: "https://geoff.ai" },
        { label: "hwonder", href: "https://www.hwonder.com/" },
        { label: "Token Plan pricing", href: "https://docs.geoff.ai/token-plan/pricing" },
        { label: "Token Plan overview", href: "https://docs.geoff.ai/token-plan/overview" },
        { label: "Stacknet health", href: "https://stacknet.magma-rpc.com/health" },
        { label: "Network summary", href: "https://stacknet.magma-rpc.com/network/summary" },
      ],
    },
    {
      id: "grok",
      name: "Grok",
      company: "xAI",
      color: "#a3e635",
      tagline: "Frontier API with huge context + realtime culture",
      delivers: [
        "Chat Completions-compatible API at api.x.ai",
        "Flagship coding / agentic reasoning models",
        "Imagine (image/video) + Voice APIs alongside text",
      ],
      horsepower: {
        flagship: "grok-4.5",
        context: "500k tokens (flagship)",
        maxContextLabel: "up to ~2M on Fast lanes",
        modalities: ["text", "image", "video", "voice", "code", "tools"],
        apiStyle: "OpenAI-compatible Chat Completions",
        pricingModel: "Usage per 1M tokens (tiered long-context rates)",
      },
      models: [
        {
          id: "grok-4.5",
          role: "Flagship code + agents",
          context: "500k",
          input: "$2.00 / $4.00*",
          output: "$6.00 / $12.00*",
          notes: "*Higher rate when prompt ≥ 200k tokens",
        },
        {
          id: "grok-4.3",
          role: "Long-context reasoning",
          context: "1M",
          input: "$1.25 / $2.50*",
          output: "$2.50 / $5.00*",
          notes: "Strong value reasoning lane",
        },
        {
          id: "grok-4.1-fast / code-fast",
          role: "Cheap high-volume / code",
          context: "2M / 256k",
          input: "~$0.20",
          output: "~$0.50–$1.50",
          notes: "Volume & coding specialists",
        },
      ],
      research: [
        { label: "xAI API", href: "https://x.ai/api" },
        { label: "Models docs", href: "https://docs.x.ai/developers/models" },
        { label: "Console", href: "https://console.x.ai" },
      ],
    },
    {
      id: "openai",
      name: "OpenAI",
      company: "OpenAI",
      color: "#5eead4",
      tagline: "Platform API + frontier GPT / reasoning stack",
      delivers: [
        "Responses / Chat Completions APIs for products & agents",
        "Frontier GPT-5.x family + specialized audio/realtime/image models",
        "Enterprise controls, fine-tunes, and tool ecosystems",
      ],
      horsepower: {
        flagship: "gpt-5.6 Sol",
        context: "up to ~1.05M on GPT-5.x production lanes",
        maxContextLabel: "~1.05M tokens",
        modalities: ["text", "image", "audio", "realtime", "code", "tools", "search"],
        apiStyle: "OpenAI API (Responses + Chat Completions)",
        pricingModel: "Usage per 1M tokens (varies widely by tier)",
      },
      models: [
        {
          id: "gpt-5.6 Sol",
          role: "Highest reasoning ceiling",
          context: "Frontier / preview",
          input: "See docs",
          output: "See docs",
          notes: "Complex pro work, coding, long agents",
        },
        {
          id: "gpt-5.6 Terra / Luna",
          role: "Balanced / cost lanes",
          context: "Frontier / preview",
          input: "See docs",
          output: "See docs",
          notes: "Default vs high-volume cost-sensitive",
        },
        {
          id: "gpt-5.5 / gpt-5.4",
          role: "Stable production",
          context: "~1.05M",
          input: "~$2.50–$5",
          output: "~$15–$30",
          notes: "GA workhorses; Pro tiers much higher",
        },
      ],
      research: [
        { label: "Models catalog", href: "https://platform.openai.com/docs/models" },
        { label: "Pricing", href: "https://openai.com/api/pricing/" },
        { label: "Status", href: "https://status.openai.com" },
      ],
    },
    {
      id: "copilot",
      name: "GitHub Copilot",
      company: "Microsoft / GitHub",
      color: "#86efac",
      tagline: "Multi-model coding cockpit inside the IDE",
      delivers: [
        "Inline + chat + agent coding across VS Code, JetBrains, CLI, github.com",
        "Model picker spanning OpenAI, Anthropic, Google (plan-gated)",
        "Enterprise policy controls for which models orgs can enable",
      ],
      horsepower: {
        flagship: "GPT-5.6 Sol (in Copilot) + Claude Sonnet 5 / Opus lanes",
        context: "Model-dependent (provider windows)",
        maxContextLabel: "Provider max (often 200k–1M+)",
        modalities: ["code", "text", "agents", "repo context", "CLI"],
        apiStyle: "Product UX (not a raw public LLM API)",
        pricingModel: "Seat plans: Free / Pro / Pro+ / Business / Enterprise",
      },
      models: [
        {
          id: "GPT-5.6 Sol / Terra / Luna",
          role: "OpenAI coding tiers",
          context: "Provider",
          input: "Seat plan",
          output: "Seat plan",
          notes: "Sol often gated to higher SKUs",
        },
        {
          id: "Claude Sonnet 5 / Opus 4.x",
          role: "Anthropic coding & agents",
          context: "Provider",
          input: "Seat plan",
          output: "Seat plan",
          notes: "Strong IDE/agent lanes; ZDR on many Sonnets",
        },
        {
          id: "Gemini 3.x Flash / Pro",
          role: "Google speed & pro",
          context: "Provider",
          input: "Seat plan",
          output: "Seat plan",
          notes: "Flash for speed; Pro for heavier reasoning",
        },
      ],
      research: [
        {
          label: "Supported models",
          href: "https://docs.github.com/en/copilot/reference/ai-models/supported-models",
        },
        { label: "Plans & pricing", href: "https://github.com/features/copilot/plans" },
        { label: "GitHub Status", href: "https://www.githubstatus.com" },
      ],
    },
    {
      id: "opencode",
      name: "OpenCode · Zen/Go",
      company: "Anomaly · opencode.ai",
      color: "#67e8f9",
      tagline: "Agent-native coding shelf · free tier with a published leash",
      delivers: [
        "Free shelf: Big Pickle plus promo models at 200 requests/day — cap stated in their own FAQ",
        "Go upsell: $5 first month then $10/mo — capacity framed as roughly $12 per 5h / $30 weekly / $60 monthly",
        "Per-model call ladder spans ~110 (premium) to 45,300+ (cheap shelf) per rolling 5-hour window; tier tabs 1×–250×",
        "Zen is a separate pay-as-you-go credit pool — not the same meter as Go",
        "Disclosure duty: several shelf models are anonymous relabels; paper specs are public via models.dev, upstream identities are not",
      ],
      horsepower: {
        flagship: "big-pickle (anonymous)",
        context: "200k pickle · 1M promo slots",
        maxContextLabel: "1M on Ox Alpha Free / Muse Spark",
        modalities: ["code", "text", "agents", "tools"],
        apiStyle: "Agent/CLI-first · OpenAI-compatible endpoints",
        pricingModel: "Free 200 req/day · Go $5→$10/mo · Zen pay-as-you-go",
      },
      models: [
        {
          id: "big-pickle",
          role: "Free reasoning ghost",
          context: "200k",
          input: "free*",
          output: "free*",
          notes: "*200 req/day cap · upstream unnamed · knowledge cutoff Jan 2025 · closed weights",
        },
        {
          id: "Ox Alpha Free",
          role: "Limited-time unlimited promo",
          context: "1M",
          input: "$0",
          output: "$0",
          notes: "Stealth slot · can vanish whenever the promo ends",
        },
        {
          id: "Go paid ladder",
          role: "Kimi K3 → Muse Spark lineup",
          context: "varies",
          input: "Go plan",
          output: "Go plan",
          notes: "110 → 45,300 calls / 5h by model · Hy3 carries an 8× usage badge",
        },
      ],
      research: [
        { label: "Go price sheet", href: "https://opencode.ai/go" },
        { label: "Zen catalog", href: "https://opencode.ai/zen" },
        { label: "models.dev registry", href: "https://models.dev/" },
        { label: "GitHub (Anomaly)", href: "https://github.com/anomalyco/opencode" },
      ],
    },
  ],
  dimensions: [
    {
      id: "unit",
      label: "Unit of power (non-apples)",
      blurb: "What you’re actually buying — shared pool, per-call meter, or a seat.",
      scores: {
        geoff: "Universal Token Plan pool",
        opencode: "Free daily quota + $10/mo sub",
        grok: "$ / 1M token meter",
        openai: "$ / 1M token meter",
        copilot: "Monthly product seat",
      },
    },
    {
      id: "menu",
      label: "Public model menu",
      blurb: "OpenAI-style /v1/models cards vs internal routing lanes.",
      scores: {
        geoff: "5 API cards · ~29 net lanes",
        opencode: "Public registry · ghosts included",
        grok: "Docs model ids",
        openai: "Large model catalog",
        copilot: "Seat-gated menu",
      },
    },
    {
      id: "api",
      label: "API access coverage",
      blurb: "Can you call models programmatically (Chat Completions-style)?",
      scores: { geoff: "Partial / network", opencode: "Yes — agent/CLI-first", grok: "Yes", openai: "Yes", copilot: "Product only" },
    },
    {
      id: "context",
      label: "Context limits",
      blurb: "How much fits in one prompt/session — your deductible on memory.",
      scores: {
        geoff: "Lane-dependent",
        opencode: "200k free · 1M promos",
        grok: "500k–2M",
        openai: "~1.05M on GPT-5.x",
        copilot: "Provider window",
      },
    },
    {
      id: "multimodal",
      label: "Multimodal riders",
      blurb: "Same wallet across modalities — or siloed SKUs?",
      scores: {
        geoff: "One pool · text→music→video",
        opencode: "Text/code first",
        grok: "Text + image/video/voice",
        openai: "Text + image/audio/realtime",
        copilot: "Code-first (+ chat)",
      },
    },
    {
      id: "story",
      label: "Story / creative lane",
      blurb: "Quiet utility for narrative work — guide, widen, keep the author in the chair.",
      scores: {
        geoff: "Shadow booster · multimodal",
        opencode: "Code story, not film",
        grok: "Strong chat + media",
        openai: "Strong chat + media",
        copilot: "Code story, not film",
      },
    },
    {
      id: "agents",
      label: "Agent / tools coverage",
      blurb: "MCP, tool calling, IDE agents, sandboxes — who shows up when work gets messy.",
      scores: {
        geoff: "MCP + widgets + sandboxes",
        opencode: "Core purpose — agent runner",
        grok: "Strong tool calling",
        openai: "Tools + Responses agents",
        copilot: "IDE/cloud coding agents",
      },
    },
    {
      id: "price",
      label: "Premium style",
      blurb: "How the bill shows up — compare shape, not fake dollar twins.",
      scores: {
        geoff: "Token Plan $19–$999/mo",
        opencode: "200/day free · $10/mo Go",
        grok: "$ / 1M tokens",
        openai: "$ / 1M tokens",
        copilot: "Monthly seats",
      },
    },
    {
      id: "transparency",
      label: "Public receipts",
      blurb: "What you can verify without pledging allegiance (or a credit card).",
      scores: {
        geoff: "High — live vitals",
        opencode: "Mixed — registry open, upstreams hidden",
        grok: "Medium — docs, auth API",
        openai: "Medium — status + docs",
        copilot: "Medium — model list, seat fog",
      },
    },
    {
      id: "modularity",
      label: "Modular vs sealed",
      blurb: "Can you strap modules on — or only renew the appliance?",
      scores: {
        geoff: "Strap-on / network",
        opencode: "Any-agent · BYO harness",
        grok: "API modules",
        openai: "Platform APIs",
        copilot: "Sealed cockpit",
      },
    },
  ],
};
